### ISSUE TITLE
install-complete.txt isn't written after completed unless setup folder pre-exists.

### ISSUE THREAD

**Issue by leblancmeneses** [cdandoy/DbPop#52]
I had a setup post hook to write done.complete, however, it seems the tool provides this feature.

However, it only writes the file, 'install-complete.txt', if I have a "setup" folder otherwise the file is not written.

I expected the file to get created on completed regardless if a setup folder "pre" exists.

**Comment by cdandoy** [comment]
The setup "hooks" are in the setup directory.
I assume your "post hook" is in `.../setup/post-install.sh`

If your dbpop config directory looks like this:
```
+-- dbpop
   +-- setup
       +-- post-install.sh
```

Start dbpop and you should see this:
```
+-- dbpop
   +-- setup
       |-- install-complete.txt
       +-- post-install.sh
```

**Comment by leblancmeneses** [comment]
I no longer need the setup folder if your tool is writing install-complete.txt.  That is all my post-install.sh script was doing.  After deleting the setup folder install-complete.txt is no longer written. 

The setup folder should be optional if the user is not supplying any hooks.

**Comment by cdandoy** [comment]
cannot reproduce
